import LoginForm from '@/components/LoginPage/LoginForm/LoginForm';
import SocialLogin from '@/components/RegisterPage/SocialLogin/SocialLogin';
import Link from 'next/link';

export const metadata = {
    title: 'Login - Nexus Media',
    description: 'Generated by Nexus Media Login Page'
};

const LoginPage = () => {
    return (
        <>
            <LoginForm />
            <div className='my-3 text-base italic text-center text-gray-300'>
                Create a new account?{' '}
                <Link className='text-blue-500' href='/register'>
                    Register
                </Link>
            </div>

            {/* Social Login */}
            <SocialLogin />
        </>
    );
};

export default LoginPage;
