import './globals.css';
import { Poppins } from 'next/font/google';
import NextProvider from '@/Providers/NextProvider';
import ThemeProvider from '../Providers/ThemeContext';
import { Toaster } from 'sonner';
import RadixThemeProvider from '@/Providers/RadixThemeProvider';
import SessionProvider from '@/Providers/SessionProvider';

const poppins = Poppins({
    weight: ['200', '400', '500', '600', '700', '800'],
    subsets: ['latin'],
    display: 'swap'
});

export const metadata = {
    title: 'Nexus Media',
    description: 'Generated by Nexus Media'
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${poppins.className}`}>
                <NextProvider>
                    <ThemeProvider>
                        <SessionProvider>
                            <RadixThemeProvider>
                                {children}
                                <Toaster position='top-right' />
                            </RadixThemeProvider>
                        </SessionProvider>
                    </ThemeProvider>
                </NextProvider>
            </body>
        </html>
    );
}
