import RegisterForm from '@/components/RegisterPage/RegisterForm/RegisterForm';
import Link from 'next/link';

export const metadata = {
    title: 'Register - Nexus Media',
    description: 'Generated by Nexus Media Register Page'
};

const RegisterPage = () => {
    return (
        <>
            <RegisterForm />

            <div className='my-3 text-base italic text-center text-gray-300'>
                Already have a account?{' '}
                <Link className='text-blue-500' href='/login'>
                    Login
                </Link>
            </div>
        </>
    );
};

export default RegisterPage;
