import Button from '@/components/Button/Button';
import FormControl from '@/components/RegisterPage/FormControl/FormControl';
import FormPassword from '@/components/RegisterPage/FormControl/FormPassword';
import FormHading from '@/components/RegisterPage/FormHading/FormHading';
import React from 'react';

export const metadata = {
    title: 'Register || Nexus Media',
    description: 'Generated by Nexus Media Register Page'
};

const RegisterPage = () => {
    return (
        <form>
            <FormHading>Create a new account</FormHading>
            <div className='py-3'>
                <FormControl label='Name' id='name' type='text' placeholder='Enter Your Name' />
                <FormControl
                    label='Email'
                    id='email'
                    type='email'
                    placeholder='example@gmail.com'
                />
                <FormPassword label='Password' id='password' placeholder='Enter Your Password' />
            </div>
            <Button className='w-full mt-2 hover:opacity-75 bg-gradient-to-r from-violet-500 to-fuchsia-500'>
                Register
            </Button>
        </form>
    );
};

export default RegisterPage;
